a[101];i,j,k,t;s;
main(n,m)
{
  for(scanf("%d%d",&n,&m);~scanf("%d",a+i++););
  for(i=0;i<n-2;i++)
  {
    for(j=i+1;j<n-1;j++)
    {
      for(k=j+1;k<n;k++)
      {
        t=a[i]+a[j]+a[k];
        s=t>m||s>t?s:t;
      }
    }
  }
  printf("%d",s);
}
